---
title: "graphs_testing"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
here::i_am("graphs_test.qmd")

path <- here::here("scripts")            # scripts source
source_files <- list.files(path, "*.R$")  # locate all .R files
map(paste0(path, "/", source_files), source)  # source all .R scripts
```

```{r}
source(here("scripts","fed-funds-rate-graph.R"))
```

```{r, eval = F}
library(ustyc)
#fix(getYieldCurve)
yc <- getYieldCurve()
```

```{r, eval = F}
library(YieldCurve)
# fix at https://github.com/mrbcuda/ustyc/issues/1 
yc <- getYieldCurve()
```

```{r}
library(Quandl)
yc <- Quandl("USTREASURY/YIELD")
yield_curve <- yc %>% 
  rename("1 month" = `1 MO`,
         "2 months" = `2 MO`,
         "3 months" = `3 MO`,
         "6 months" = `6 MO`,
         "1 Year" = `1 YR`,
         "2 Years" = `2 YR`,
         "3 Years" = `3 YR`,
         "5 Years" = `5 YR`,
         "7 Years" = `7 YR`,
         "10 Years" = `10 YR`,
         "20 Years" = `20 YR`,
         "30 Years" = `30 YR`) %>%
  slice(1) %>%
  pivot_longer(cols = 2:13, names_to = "maturity") %>%
  mutate(maturity = ordered(maturity,
                           levels = c("1 month", "2 months", "3 months", "6 months", "1 Year", "2 Years", "3 Years", "5 Years", "7 Years", "10 Years", "20 Years", "30 Years")
                           )) %>%
  ggplot()+
  aes(x = maturity,
      y = value)+
  geom_point(color = "red")+
  geom_path(aes(x = as.numeric(maturity), y = value), color = "red", size = 2)+
  #annotate(x = 10, y = 4.5, geom = "text", label = "As of April 6, 2023", color = "red")+
  labs(x = "Maturity",
       y = "Yield",
       title = "U.S. Treasury Yield Curve",
       caption = paste0("As of ",yc$Date[1]))+
  scale_y_continuous(breaks = seq(0,10,0.5),
                     labels = scales::label_percent(scale = 1))+
  theme_bw(base_family = "Fira Sans Condensed", base_size = 14)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

yield_curve
```

```{r}
yield_curve %>% plotly::ggplotly()
```

```{r}
yc_reg <- yc %>%
  slice(1) %>%
  rename("1" = `1 MO`,
         "2" = `2 MO`,
         "3" = `3 MO`,
         "6" = `6 MO`,
         "12" = `1 YR`,
         "24" = `2 YR`,
         "36" = `3 YR`,
         "60" = `5 YR`,
         "84" = `7 YR`,
         "120" = `10 YR`,
         "240" = `20 YR`,
         "360" = `30 YR`) %>%
  slice(1) %>%
  pivot_longer(cols = 2:13, names_to = "maturity") %>%
  mutate(maturity = as.numeric(maturity)) %>%
  lm(value ~ maturity, data = .) %>%
  broom::tidy()

yc_reg_slope <- yc_reg %>%
  filter(term == "maturity") %>%
  pull(estimate)
  
yc_slope <- if_else(yc_reg_slope > 0,
                       "normal",
                       "inverted")

yc_slope
```
