---
title: "graphs"
format: html
editor: visual
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(fredr)
library(fontawesome)
library(dygraphs)
library(extrafont)

fredr_set_key("9100cdf3c862283007d8c83ce02059e6")

recessions <-fredr(
    series_id = "JHDUSRGDPBR"
)

recessions_start_end <- recessions %>% # from https://datavizm20.classes.andrewheiss.com/example/11-example/
    mutate(recession_change = value - lag(value)) %>% 
    filter(recession_change != 0)

recs <- tibble(start = filter(recessions_start_end, recession_change == 1)$date,
               end = filter(recessions_start_end, recession_change == -1)$date)
```

```{r, import-values}

# Federal Funds Rate

ffr<-fredr(
  series_id = "FEDFUNDS"
)

#  US Regular All Formulations Gas Price
gas <- fredr(
  series_id = "GASREGW"
)

#  University of Michigan: Consumer Sentiment
## 1966Q1 = 100 Index

conssent = fredr(
  series_id = "UMCSENT"
)

#  Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma; Dollars per Barrel
oil = fredr(
  series_id = "DCOILWTICO"
)
```

```{r get-latest-value-and-date-functions}
get_latest_value = function(input){
  input %>%
    arrange(desc(date)) %>%
    slice(1) %>%
    pull(value)
}

get_latest_date = function(input){
  input %>%
    arrange(desc(date)) %>%
    slice(1) %>%
    pull(date) -> temp
    paste(lubridate::month(temp, label = TRUE),
            lubridate::day(temp),
            lubridate::year(temp))
}
```

```{r}
plot_ffr <-ggplot(data = ffr)+
    aes(x = date,
        y = value,
        color = series_id)+
    geom_rect(data = recs, 
              aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
              inherit.aes = FALSE, fill = "black", alpha = 0.3)+
    geom_path(size=1)+
    geom_hline(yintercept=0, size=1)+
    scale_x_date(limits=as.Date(c("1955-01-01", "2022-07-01")),
                 date_breaks = "5 years",
                 #minor_breaks = "2 years",
                 date_labels = "%Y",
                 expand = c(0,0))+
    scale_y_continuous(breaks=seq(0,20,2),
                       labels=function(x){paste0(x,"%")},
                       limits = c(0,20),
                       expand = c(0,0))+
    labs(x = "Year",
         y = "Federal Funds Rate",
         caption = bquote("Data Source: FRED; Recessions Shaded in Gray; Latest Release: " ~ .(get_latest_date(ffr))
                 )
         )+
    theme_classic(base_family = "Fira Sans Condensed", base_size = 16)+
    theme(legend.position="none")

plot_ffr # %>% plotly::ggplotly()

```

```{r}
plotly::ggplotly(plot_ffr)
```

## Dygraphs

```{r}
library(xts)
ffr %>% 
  select(value) %>%
  rename("Fed Funds Rate" = value) %>% 
  xts(., order.by = as.Date(ffr$date)) %>% 
  dygraph() %>%
  dyRangeSelector()
```

## Hicharter

```{r}
library(highcharter)
hchart(ffr, "line", hcaes(x = date, y = value))
```